ktor:
  deployment:
    port: 8000
    host: 0.0.0.0

  application:
    modules:
      - com.pollyannawu.justwoo.backend.DiModuleKt.diModule

database:
  host: ${DB0_PORT:mem}
  port: ${DB0_HOST:5432}
  user: $DB0_USERNAME:sa}
  password: ${DB0_PASSWORD:}
  dbName: ${DB0_NAME:test}

jwt:
  secret: ${JWT_SECRET:-my-super-secret-12345}
  issuer: "https://justwoo.api.com"
  audience: "justwoo-users"
  realm: "access to justwoo"

  poolSize: 5