ktor:
  deployment:
    port: ${PORT:8000}
    host: ${HOST:0.0.0.0}
    forwardedHeaderSupport: true

  application:
    modules:
      - com.pollyannawu.justwoo.backend.DiModuleKt.diModule

database:
  host: ${DB_HOST}
  port: ${DB_PORT:5432}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dbName: ${DB_NAME}
  maximumPoolSize: ${DB_POOL_SIZE:5}

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER:https://justwoo.api.com}
  audience: ${JWT_AUDIENCE:justwoo-users}
  realm: ${JWT_REALM:access to justwoo}